### ISSUE TITLE
Strict types enforces strict typing for userland helpers since 2.17

### ISSUE THREAD

**Issue by rutek** [laminas/laminas-view#124]
### BC Break Report

|    Q        |   A
|------------ | ------
| laminas-view version | 2.17+
| PHP version | 7.4

#### Summary

Laminas View component has been updated to match Laminas Coding Standards in version 2.17. It included adding `strict_types=1` to every class. It breaks userland code enforcing strict types to helper calls. I noticed it for custom helpers but it needs further investigation as it may have more downsides.

From my testing it's directly caused by `declare(strict_types=1);` in `PhpRenderer` as template file is included so it's enforced to be strictly typed. 

From my perspective, such behavior is needed but maybe in 3.x as users will experience breaking change during regular 2.x updates.

#### Previous behavior

All helpers extending `AbstractHelper` can have strict_types disabled.

#### Current behavior

All helpers extending `AbstractHelper` must have strict_types enabled.

#### How to reproduce

Only reproducible when using helper inside template rendered by `PhpRenderer`.

Create example helper with typed parameter `int $value` and use it inside template with `'123'` value.

I uploded test project to https://github.com/rutek/laminas-view-bug

Project contains dependency to v2.16 and works. Changing it to v2.17+ triggers following error:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to App\ExampleHelper::__invoke() must be of the type int, string given
```

**Comment by Ocramius** [comment]
> #### Current behavior
> 
> All helpers extending `AbstractHelper` must have strict_types enabled.

Not really: they just need to respect the types declared in the interface/abstract types, which have been in place for a decade now.

**Comment by rutek** [comment]
@Ocramius I don't refer to types declared in `AbstractHelper` nor `HelperInterface`. I am writing about all types hinted in any possible place inside helper which has been created by user. Especially arguments of `__invoke` method.

I agree that matching types is way to go but let's be honest - enforcing strict types during regular update (not some bigger version) is not a way to go. Especially when user will not know that it is enforced as his/her own file does not contain strict types definition.

**Comment by Xerkus** [comment]
This is not so much due to strict types of helpers but from helper accessed via `__call()` magic method in php renderer which defines strict types.
 
https://github.com/laminas/laminas-view/blob/5f2ed1af896543e986090afb6433e32409c99d4d/src/Renderer/PhpRenderer.php#L402-L411

Problem of incorrect types passed around until they smash into type declaration in strict context won't be solved by removing strict types in php renderer. This would need to be fixed in the userland code.
