### ISSUE TITLE
Remove FlashMessenger view helper

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-view#16]
Remove FlashMessenger view helper as requested by https://github.com/zendframework/zend-mvc-plugin-flashmessenger/issues/3 

Complementary port to MVC Plugin PR is at https://github.com/zendframework/zend-mvc-plugin-flashmessenger/pull/10

---

Originally posted by @alextech at https://github.com/zendframework/zend-view/pull/95

**Comment by weierophinney** [comment]
needs rebase

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-view/pull/95#issuecomment-302154458

**Comment by samsonasik** [comment]
I created PR #47 for it.
