### ISSUE TITLE
Gravatar Image Helper: Implement constants for all the possible image types

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-view#161]
The replacement gravatar helper has a string argument to configure the fallback image type that must be known up-front - whilst psalm will issue an error for an invalid/unknown option, public constants provide better discoverability and are more easily documented…

_Originally posted by @froschdesign in https://github.com/laminas/laminas-view/pull/158#discussion_r841071994_

**Comment by Ocramius** [comment]
Handled in #162
