### ISSUE TITLE
Improper navigation semantics

### ISSUE THREAD

**Issue by ivyrze** [laminas/laminas-view#197]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | `^2.8`

#### Summary

When a link to the currently displayed page is rendered, it should include the `aria-current="page"` attribute.

#### Current behavior

Navigation links are not providing "current page" semantics in the accessibility tree.

#### How to reproduce

Using the screen reader of your choice, activate a menu link, then bring focus back to that same a menu element.

#### Expected behavior

Varies based on assistive technology being used. As an example, VoiceOver macOS will read a properly tagged navigation link as "current page, visited, link, Example Page".

**Comment by froschdesign** [comment]
@ivyrze 
That would indeed be a good and necessary enhancement! 👍🏻 
Would you be willing to create a pull request for this?

---

I myself use the possibility to use a partial script to render the menu or breadcrumbs:

- https://docs.laminas.dev/laminas-navigation/helpers/menu/#rendering-a-custom-menu-using-a-partial-view-script
- https://docs.laminas.dev/laminas-navigation/helpers/breadcrumbs/#rendering-using-a-partial-view-script

…but in the end it is only a workaround.
