### ISSUE TITLE
v2 docs need to be reset in v3 branch

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-view#223]
Various patches in v3 have amended or removed docs, when what we actually need is a duplicated tree in v3.

In the v3 branch, docs need to be reset to the state of current 2.x and then a copy of these docs updated to reflect changes already present in v3

**Comment by froschdesign** [comment]
@gsteel 
What is missing, for example?

I see that `GravatarImage` is not listed in the navigation but it is rendered: https://docs.laminas.dev/laminas-view/v2/helpers/gravatar-image/

**Comment by gsteel** [comment]
In 3.0.x the docs have been updated in-place instead of working on a duplicate tree, so when v3 is released, the v2 docs will be for v3 code.

**Comment by gsteel** [comment]
Closed via #224
