### ISSUE TITLE
HeadScript: importmap data incorrectly escaped

### ISSUE THREAD

**Issue by matbech** [laminas/laminas-view#242]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.34 / 3.x

#### Summary

HeadScript incorrectly escapes the data when the type is set to importmap.

#### Current behavior

HeadScript escapes the data with //<![CDATA[  respectively //<!--

#### How to reproduce

```
<?php
$this->headScript()->captureStart(type: 'importmap');
?>{ "imports": {
	"fast_qr": "/static/ajax/libs/fast_qr/fast_qr.js"
} }<?php
$this->headScript()->captureEnd();
?>
```
Output
```
<script type="importmap">
<![CDATA[
{ "imports": {
	"fast_qr": "/static/ajax/libs/fast_qr/fast_qr.js"
} }
//]]>
</script>
```

#### Expected behavior

When the type is importmap, the data should not be escaped with CDATA/etc, instead the data should be encoded using HTML entities.
Output
```
<script type="importmap">
{ "imports": {
	"fast_qr": "/static/ajax/libs/fast_qr/fast_qr.js"
} }
</script>
```

#### Proposed fixed
Certain types like "importmap" or "text/x-jquery-tmpl" should automatically imply "noescape" -> true

**Comment by Xerkus** [comment]
This is not a bug.

https://docs.laminas.dev/laminas-view/v2/helpers/head-script/

> Preventing HTML style comments or CDATA wrapping of scripts
>
> By default, HeadScript will wrap scripts with HTML comments or it wraps scripts with XHTML CDATA. This behavior can be problematic when you intend to use the script tag in an alternative way by setting the type to something other then text/javascript. To prevent such escaping, pass an noescape with a value of true as part of the $attrs parameter in the method calls.
