### ISSUE TITLE
PhpRenderer @method for layout() return type is incomplete

### ISSUE THREAD

**Issue by InvisibleSmiley** [laminas/laminas-view#247]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.35.x, 3.0.x

#### Summary

`PhpRenderer` `@method` for method `layout()` is incomplete. The method actually returns `ModelInterface|Layout`, cf. `Layout::__invoke`. Actually the annotation there is wrong, too, since it never returns `null`.

https://github.com/laminas/laminas-view/blob/3.0.x/src/Renderer/PhpRenderer.php#L72
https://github.com/laminas/laminas-view/blob/3.0.x/src/Helper/Layout.php#L38

https://github.com/laminas/laminas-view/blob/2.35.x/src/Renderer/PhpRenderer.php#L76
https://github.com/laminas/laminas-view/blob/2.35.x/src/Helper/Layout.php#L38

#### Current behavior

Static analysis of code calling `PhpRenderer::layout()` and passing the result to `PhpRenderer::render()` fails

#### How to reproduce

```
<?php
$renderer = new \Laminas\View\Renderer\PhpRenderer();
$renderer->render($renderer->layout());
```

#### Expected behavior

Static analysis reports no error with the example code

**Comment by gsteel** [comment]
A patch would be most welcome 👍
