### ISSUE TITLE
laminas-view still not usable for <2.5

### ISSUE THREAD

**Issue by antiphp** [laminas/laminas-view#34]
### Bug Report

I used ZF version <2.5 and did the migration to Laminas (laminas-migration). However laminas/laminas-view:<2.5 (which resolves to 2.4.13) still contains Zend namespace. There is a 2.4.13p1 release that fixes the namespace, but <2.5 resolves to 2.4.13 and not 2.4.13p1 (I dont know what p1 should mean) and 2.4.13p1 does itself not resolve the dependency to laminas/laminas-eventmanager 2.4.13p1 (does not exist).

|    Q        |   A
|------------ | ------
| Version(s)  | 2.4.13, 2.4.13p1, <2.5

#### Summary

Laminas-view unusable below 2.5

#### How to reproduce

For <2.5 / 2.4.13:
```
composer init --no-interaction
composer require "laminas/laminas-view:<2.5"

php -r 'require "vendor/autoload.php"; new \Zend\View\View();'
# PHP Fatal error:  Cannot declare class Zend\View\View [..]

php -r 'require "vendor/autoload.php"; new \Laminas\View\View();'
# PHP Warning:  Class 'Laminas\View\View' not found
```

For 2.4.13p1 (which fixes the issue above technically I assume):
```
composer init --no-interaction
composer require "laminas/laminas-view:2.4.13p1"
#   Problem 1
#    - Installation request for laminas/laminas-view 2.4.13p1 -> satisfiable by laminas/laminas-view[2.4.13p1].
#    - laminas/laminas-view 2.4.13p1 requires laminas/laminas-eventmanager 2.4.13p1 -> no matching package found.
```

#### Expected behavior

Laminas <2.5 can be used the same way as ZF <2.5.

**Comment by michalbundyra** [comment]
@antiphp 

Can you check it again please?
I think it has been solved with 2.4.13p2.
I've tried on mine and this is what I have installed:

```
$ composer show
laminas/laminas-eventmanager         2.4.13  
laminas/laminas-loader               2.4.13  
laminas/laminas-stdlib               2.4.13  
laminas/laminas-view                 2.4.13p2 provides a system of helpers, output filters, and variable escaping
laminas/laminas-zendframework-bridge 1.0.3    Alias legacy ZF class names to Laminas Project equivalents.
```

PHP 7.3.11
Composer 1.10.5

We had there wrong requirements and it should be already fixed.

Thanks for reporting.

**Comment by samsonasik** [comment]
I tried it and working fine in my side:

![Screen Shot 2020-08-10 at 8 03 25 AM](https://user-images.githubusercontent.com/459648/89745738-08991100-dae0-11ea-851f-f4b194c7bc2b.png)

I am closing it.

**Comment by antiphp** [comment]
It works for me as well, thank you!
