### ISSUE TITLE
Typo in laminas-view/helpers

### ISSUE THREAD

**Issue by tbuerli** [laminas/laminas-view#45]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.11.4

#### Summary

The current documentation is inconsistent with uppercase and lowercase.
Therefore the example isn't working.

#### How to reproduce

On the page:
https://docs.laminas.dev/laminas-view/helpers/advanced-usage/#writing-custom-helpers

#### Current behavior
The registration gets described with the following words:
```html
Then assume that we register it with the plugin manager by the name "specialpurpose".
```

#### Expected behavior
But should be:
```html
Then assume that we register it with the plugin manager by the name "specialPurpose".
```

Because in the next code block it gets used as:
```php
echo $this->specialPurpose();
```

**Comment by froschdesign** [comment]
@tbuerli 
Thanks for reporting this problem.
It would be great if you could create a pull request. Thanks in advance!

**Comment by tbuerli** [comment]
@froschdesign 
I created a pull request https://github.com/laminas/laminas-view/pull/46
