### ISSUE TITLE
Using Zend-view with PHP STAN

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-view#5]
Currently i am using the zend view in my project and i notice a very small problem with the docblock of the \Zend\View\Model\ViewModel class constructor.
Where it says @param  null|array|Traversable $variables should be @param  null|array|Traversable|ArrayAccess $variables

In the same constructor if no $variables is provided the constructor initializes it with one instance of arrayAccess. 

---

Originally posted by @vitorloureiro at https://github.com/zendframework/zend-view/issues/183

**Comment by weierophinney** [comment]
Yes, you are right, cause method setVariables, which is called, also define ArrayAccess in DocBlock

---

Originally posted by @dennybrandes at https://github.com/zendframework/zend-view/issues/183#issuecomment-521268380

**Comment by samsonasik** [comment]
I've created PR https://github.com/laminas/laminas-view/pull/52 for it which add `ArrayAccess` to `ViewModel` $variables parameter docblock.
