### ISSUE TITLE
type in script tags for classic scripts (js) should be ommited

### ISSUE THREAD

**Issue by DennisDobslaf** [laminas/laminas-view#51]
Referring to:
https://html.spec.whatwg.org/multipage/scripting.html#the-script-element

The type attribute text/javascript is unnecessary and should be ommited.

But it seems, there is no option to get rid of it:

https://github.com/laminas/laminas-view/blob/313e1c7b20094ebe79e12db420f6b793aca93206/src/Helper/HeadScript.php#L174

**Comment by froschdesign** [comment]
Fixed with #53 and released with version [1.11.5](https://github.com/laminas/laminas-view/releases/tag/2.11.5).
