### ISSUE TITLE
`2.12.x` branch to be renamed `2.13.x`, `2.12.x` to be re-created from `2.12.0`

### ISSUE THREAD

**Issue by Ocramius** [laminas/laminas-view#71]
The current `2.12.x` branch is effectively `2.13.x`, and should **not** be released as-is.

TODOs:

 * [ ] rename `2.12.x` to `2.13.x`
 * [ ] fix `2.13.x` build (fails on markdown linting)
 * [ ] re-create `2.12.x` from `2.12.0` tagged release
 * [ ] move issues from milestone `2.12.1` to milestone `2.13.0`

**Comment by gsteel** [comment]
#72 Should solve the markdown linting problem but may well require review from @froschdesign … I've setup some linting rules to help the docs pass with as little modification to the existing docs as possible so there's not too much noise and those rules may or may not be OK

**Comment by gsteel** [comment]
Perhaps we can get 2.13.x out the door if I re-open _(and fix)_  #72 - Maybe I could ask for a bit of help from @froschdesign or @weierophinney on the docs formatting??? That would get CI working nice and allow other pulls to be pushed thru :D

**Comment by froschdesign** [comment]
@gsteel 
You can re-open #72 but all changes to the line lengths must be revert. The configuration for the markdownlint is already [updated](https://github.com/laminas/laminas-continuous-integration-action/blob/bf7d42f3d8eb1a0b817ded98db13cfc899f4440e/etc/markdownlint.json#L3).
The special Markdown syntax for [tabs](https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/) can be excluded from the linting via the [HTML comments](https://github.com/DavidAnson/markdownlint#configuration).

**Comment by weierophinney** [comment]
I'm a bit confused at this point. I think we can go forward with 2.12.1 from the current state of 2.12.x, as it has 7 PRs already merged against it, all since 2.12.0 was released, and that will then create the 2.13.x branch. We can then re-target existing PRs that we've tagged for 2.13.0 against that.
