### ISSUE TITLE
[PHP 8.1] Uncaught Return type of Laminas\View\Model\ViewModel::count()

### ISSUE THREAD

**Issue by fabiang** [laminas/laminas-view#79]
Full error message:

> Fatal error: During inheritance of Countable: Uncaught Return type of Laminas\View\Model\ViewModel::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Seems like they added `int` as return type to `Countable` interface. Guess Laminas must add `#[ReturnTypeWillChange]` attribute so not to break compatibility with PHP 5. I'm pretty sure this change affects many Laminas components.

**Comment by matbech** [comment]
The same issue has been addressed in a recent commit in stdlib:
https://github.com/laminas/laminas-stdlib/commit/c53d8537f108fac3fae652677a19735db730ba46#diff-04413b84f454666b559ddb848ef83273148267862313b28090db4af81eded901R189

**Comment by froschdesign** [comment]
Fixed with #81
