### ISSUE TITLE
JsonViewModel causes double-slash when returning file paths

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-view#9]
As per the title, when setting a variable to the view that contains a file path, the directory separators are escaped resulting in a double-slash in the returned response body (on win 10 running zend server 9). Is there any way to set the view to use the constant JSON_UNESCAPED_SLASHES?

---

Originally posted by @bogal at https://github.com/zendframework/zend-view/issues/141

**Comment by weierophinney** [comment]
you may need to extends the `JsonModel` and override the `serialize()` function

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-view/issues/141#issuecomment-379336196

**Comment by samsonasik** [comment]
I'm closing it as can be achieved by extends the JsonModel and override the serialize() function.
